# Generated by Django 4.1.6 on 2023-02-14 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('mobile_number', models.IntegerField()),
                ('area_locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=3, null=True)),
                ('order_id', models.CharField(max_length=32, null=True)),
                ('receipt', models.CharField(max_length=32, null=True)),
                ('payment_capture', models.IntegerField(default=0, null=True)),
                ('payment_id', models.CharField(max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_image_1', models.ImageField(upload_to='product_images')),
                ('product_image_2', models.ImageField(upload_to='product_images')),
                ('product_image_3', models.ImageField(upload_to='product_images')),
                ('product_image_4', models.ImageField(upload_to='product_images')),
                ('product_image_5', models.ImageField(upload_to='product_images')),
                ('product_selling_price', models.IntegerField()),
                ('product_discounted_price', models.IntegerField()),
                ('product_description', models.TextField(max_length=1000)),
                ('product_suitable_for', models.CharField(max_length=200)),
                ('product_brand', models.CharField(max_length=50)),
                ('product_seller', models.CharField(max_length=50)),
                ('product_category', models.CharField(choices=[('cloth', 'cloth'), ('emitation_jewellery', 'emitation_jewellery'), ('topi', 'topi'), ('rida', 'rida')], max_length=20)),
                ('product_sub_category', models.CharField(choices=[('rida', 'rida'), ('kurta_izar', 'kurta_izar'), ('night_dress', 'night_dress')], max_length=20)),
                ('product_upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SliderBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image_1', models.ImageField(upload_to='banner_image')),
                ('banner_image_2', models.ImageField(upload_to='banner_image')),
                ('banner_image_3', models.ImageField(upload_to='banner_image')),
                ('banner_image_4', models.ImageField(upload_to='banner_image')),
                ('banner_image_5', models.ImageField(upload_to='banner_image')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(default=0)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('order_placed_date', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(choices=[('Order Confirm', 'Order Confirm'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Out of Delivery', 'Out of Delivery'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Order Confirm', max_length=20)),
                ('currency', models.CharField(default='', max_length=3)),
                ('order_id', models.CharField(default='', max_length=32)),
                ('receipt', models.CharField(default='', max_length=32)),
                ('payment_capture', models.IntegerField(default=0)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burhanimart.customeraddress')),
                ('payment', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='burhanimart.payment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burhanimart.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_email', models.EmailField(max_length=100)),
                ('mobile_number', models.IntegerField()),
                ('query', models.TextField(max_length=500)),
                ('query_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burhanimart.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
