# Generated by Django 4.1.6 on 2025-05-23 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burhanimart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='payment',
        ),
    ]
